# frozen_string_literal: true

class Gouache

  D8 = / 1?\d?\d | 2[0-4]\d | 25[0-5] /x  # 0..255 string; used in a few places building regexes

  BASE_STYLES = {
    reset:              0,
    black:              30,
    red:                31,
    green:              32,
    yellow:             33,
    blue:               34,
    magenta:            35,
    cyan:               36,
    white:              37,
    default:            39,
    black!:             90,
    red!:               91,
    green!:             92,
    yellow!:            93,
    blue!:              94,
    magenta!:           95,
    cyan!:              96,
    white!:             97,
    on_black:           40,
    on_red:             41,
    on_green:           42,
    on_yellow:          43,
    on_blue:            44,
    on_magenta:         45,
    on_cyan:            46,
    on_white:           47,
    on_default:         49,
    over_default:       59,
    on_black!:         100,
    on_red!:           101,
    on_green!:         102,
    on_yellow!:        103,
    on_blue!:          104,
    on_magenta!:       105,
    on_cyan!:          106,
    on_white!:         107,
    bold:                1,
    dim:                 2,
    faint:               2,
    italic:              3,
    underline:           4,
    double_underline:   21,
    overline:           53,
    blink:               5,
    invert:              7,
    inverse:             7,
    reverse:             7,
    hidden:              8,
    hide:                8,
    conceal:             8,
    strike:              9,
    strikeout:           9,
    strikethrough:       9,
    intensity_off:      22, # dim+bold
    dim_off:            ->{ it.dim = false },
    bold_off:           ->{ it.bold = false },
    italic_off:         23,
    underlines_off:     24, # under+double
    blink_off:          25,
    invert_off:         27,
    inverse_off:        27,
    reverse_off:        27,
    hidden_off:         28,
    hide_off:           28,
    reveal:             28,
    strike_off:         29,
    strikeout_off:      29,
    strikethrough_off:  29,
    overline_off:       55,
  }

end
